<a href="https://colab.research.google.com/github/SatyaIyerRaghav/PandaPractisePrograms/blob/main/AllPractisePrograms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Swapping
Description
You are given two integer variables,  x and y. You have to swap the values stored in x and y.

----------------------------------------------------------------------
Input:
Two numbers x and y separated by a comma.

Output:
Print 5 lines. The first two lines will have values of variables shown before swapping, and the last two lines will have values of variables shown after swapping. The third line will be blank.

----------------------------------------------------------------------
Sample input:
20, 50

Sample output:
x before swapping: 20
y before swapping: 50

x after swapping: 50
y after swapping: 20

In [4]:
#Take input using input()

#input() takes input in form of the string
in_string=input()
#here extract the two numbers from the string
mylist = in_string.split(',')
x= int(mylist[0])
y= int(mylist[1])
#print x and y before swapping
print("x before swapping: {0}".format(x))
print("y before swapping: {0}".format(y))

#Writing your swapping code here
z=x
x=y
y=z

20 50


ValueError: ignored

In [3]:
i = ['abc','def','hjk','klj']
i.remove('klj')
print(i)
i.append('ooo')
print(i)

['abc', 'def', 'hjk']
['abc', 'def', 'hjk', 'ooo']


In [13]:
import numpy as np

a = np.zeros((8,8),dtype=int)
print(a.shape)
print(np.unravel_index(49, (8,8)))
print()

(8, 8)
(6, 1)


In [14]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5, 6, 7], [11, 12, 13, 14, 15, 16, 17],[21, 22, 23, 24, 25, 26, 27],[31, 32, 33, 34, 35, 36, 37]], np.int32)
print(a[ :3 , -5: ])

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]]


In [15]:
 np.arange(1,16,2).reshape(4, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])